/**
 * Spring Boot REST API
 * Spring Boot REST API for Online Store
 *
 * OpenAPI spec version: 1.0
 * Contact: leonpolq@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ConsultantInformation {
    availableFrom?: models.Time;

    availableUntil?: models.Time;

    consultantGroupUser?: models.ConsultantGroupUser;

    degree?: string;

    education?: string;

    id?: number;

    licenseFile?: string;

    licenseNumber?: string;

    licenseUntil?: Date;

}
