export * from './AssetscontrollerApi';
import { AssetscontrollerApi } from './AssetscontrollerApi';
export * from './ConsultantgroupcontrollerApi';
import { ConsultantgroupcontrollerApi } from './ConsultantgroupcontrollerApi';
export * from './ConsultantgroupusercontrollerApi';
import { ConsultantgroupusercontrollerApi } from './ConsultantgroupusercontrollerApi';
export * from './ConsultantinformationcontrollerApi';
import { ConsultantinformationcontrollerApi } from './ConsultantinformationcontrollerApi';
export * from './ConversationcontrollerApi';
import { ConversationcontrollerApi } from './ConversationcontrollerApi';
export * from './ConversationmessagecontrollerApi';
import { ConversationmessagecontrollerApi } from './ConversationmessagecontrollerApi';
export * from './ConversationstatuscontrollerApi';
import { ConversationstatuscontrollerApi } from './ConversationstatuscontrollerApi';
export * from './CustomerinformationcontrollerApi';
import { CustomerinformationcontrollerApi } from './CustomerinformationcontrollerApi';
export * from './CustomerpaymentcontrollerApi';
import { CustomerpaymentcontrollerApi } from './CustomerpaymentcontrollerApi';
export * from './ResourcecontrollerApi';
import { ResourcecontrollerApi } from './ResourcecontrollerApi';
export * from './SummarypaymentscontrollerApi';
import { SummarypaymentscontrollerApi } from './SummarypaymentscontrollerApi';
export * from './UsercontrollerApi';
import { UsercontrollerApi } from './UsercontrollerApi';
export const APIS = [AssetscontrollerApi, ConsultantgroupcontrollerApi, ConsultantgroupusercontrollerApi, ConsultantinformationcontrollerApi, ConversationcontrollerApi, ConversationmessagecontrollerApi, ConversationstatuscontrollerApi, CustomerinformationcontrollerApi, CustomerpaymentcontrollerApi, ResourcecontrollerApi, SummarypaymentscontrollerApi, UsercontrollerApi];
